In [2]:
import cocoex
import numpy as np
import cma

In [4]:
cocoex.known_suite_names.append("bbob-constrained")

In [6]:
#suite = cocoex.Suite("bbob-constrained", "", "dimensions:2,3,5 instance_indices:1")
suite = cocoex.Suite("bbob-constrained", "", "")

In [47]:
#problem = suite.next_problem()
problem=suite.get_problem_by_function_dimension_instance(50, 3, 4)
print(problem)

bbob-constrained_f050_i04_d03: a 3-dimensional single-objective problem with 3 constraints (problem 1548 of suite "b'bbob-constrained'" with name "bbob-constrained suite problem f50 instance 4 in 3D")


In [48]:
problem.constraint(problem.initial_solution)

array([-36555.4709516 , -48629.5180831 , -14324.69205331])

In [49]:
problem._best_parameter('print')
_xopt = np.loadtxt('._bbob_problem_best_parameter.txt')
_xopt

array([ 0.904 , -1.4944,  1.4664])

In [50]:
problem.constraint(_xopt)

array([     0.        , -11577.06839467,      0.        ])

In [51]:
problem(_xopt)

1039.8999999999999

## Optimize

## in a small neighbourhood around the optimum

In [52]:
es.mean

array([ 2.1152, -0.1048,  3.8176])

In [53]:
res, es = cma.fmin_con(problem, _xopt, 1e-4, g=problem.constraint)

assert np.allclose(_xopt, es.mean)

(3_w,7)-aCMA-ES (mu_w=2.3,w_1=58%) in dimension 3 (seed=916043, Thu Nov 25 16:45:16 2021)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1      7 1.039892947667564e+03 1.3e+00 1.12e-04  1e-04  1e-04 0:00.0
    2     14 1.039897169608854e+03 1.7e+00 1.13e-04  1e-04  1e-04 0:00.0
    3     21 1.039897243003969e+03 1.4e+00 1.07e-04  9e-05  1e-04 0:00.0
  100    700 1.039900000000001e+03 5.1e+00 5.50e-07  6e-09  2e-08 0:00.2
  114    798 1.039900000000000e+03 4.1e+00 2.12e-07  2e-09  3e-09 0:00.2
termination on tolfun=1e-11 (Thu Nov 25 16:45:16 2021)
final/bestever f-value = 1.039900e+03 1.039893e+03
incumbent solution: [0.9039999990462141, -1.4944000005808853, 1.4664000007870885]
std deviation: [1.6047620931201242e-09, 1.6403401785853877e-09, 2.762401266328436e-09]


## global opt. with large popsize

In [54]:
opts = cma.CMAOptions()
opts.set("popsize", 100)

cma.fmin_con(problem, np.ones(problem.dimension), 10, g=problem.constraint, options=opts)

(50_w,100)-aCMA-ES (mu_w=27.0,w_1=8%) in dimension 3 (seed=969639, Thu Nov 25 16:45:18 2021)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1    100 1.439600659321915e+03 1.3e+00 9.98e+00  5e+00  6e+00 0:00.0
    2    200 1.431523632901248e+03 1.5e+00 1.27e+01  4e+00  6e+00 0:00.0
    3    300 1.408672339704766e+03 1.7e+00 1.27e+01  3e+00  3e+00 0:00.0
   44   4400 1.089446012414870e+03 2.1e+00 5.31e+00  1e-09  2e-09 0:00.5
termination on tolflatfitness=1 (Thu Nov 25 16:45:19 2021)
final/bestever f-value = 1.089446e+03 1.042971e+03
incumbent solution: [0.5991726986183304, -2.385391896609955, 1.0907410332933112]
std deviation: [1.3341055481774753e-09, 1.2261984419125736e-09, 2.3540935128456835e-09]


(array([ 0.89121988, -1.51872357,  1.45281899]),
 <cma.evolution_strategy.CMAEvolutionStrategy at 0x7fc847e1e880>)